### ISSUE TITLE
App crash after installing the package in android

### ISSUE THREAD

**Issue by DeepikaSharma5** [a7med-mahmoud/react-native-ml-kit#12]
### What happened?

I insalled the package using npm like this
`npm install @react-native-ml-kit/image-labeling --save`

It is making the app crash. The I tried to link the main branch directly to package,json like this
` "@react-native-ml-kit/image-labeling": "https://github.com/a7med-mahmoud/react-native-ml-kit/tree/main/image-labeling#main",`

That doesn't event install

### Version

1.2.0

### Which ML Kit packages do you use?

- [ ] @react-native-ml-kit/barcode-scanning
- [ ] @react-native-ml-kit/face-detection
- [ ] @react-native-ml-kit/identify-languages
- [X] @react-native-ml-kit/image-labeling
- [ ] @react-native-ml-kit/text-recognition
- [ ] @react-native-ml-kit/translate-text

### What platforms are you seeing this issue on?

- [X] Android
- [X] iOS

### System Information

`System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 3.95 GB / 15.74 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8193401
    Visual Studio: Not Found
  Languages:
    Java: 11.0.15.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

### Steps to Reproduce

Install the package using `npm install @react-native-ml-kit/image-labeling --save`
Try run the project using  `npm run android`

**Comment by a7med-mahmoud** [comment]
Thanks for reporting this issue @DeepikaSharma5, I'll look into it and let you know.

**Comment by a7med-mahmoud** [comment]
Can you share the error that you see so I can better understand the problem?

**Comment by DeepikaSharma5** [comment]
@a7med-mahmoud That's the main issue.  I don't see any errors, warnings or info.  Just when you install the package and run the project the app is crashing. There is no information in the console.

**Comment by DeepikaSharma5** [comment]
Any update @a7med-mahmoud ?

**Comment by a7med-mahmoud** [comment]
I created a new React Native 0.69.4 app and installed `@react-native-ml-kit/image-labeling` and ran the app on Android and it does work properly.
What Android API of the emulator are you using?

**Comment by DeepikaSharma5** [comment]
I am also using the same react -native version. And I am running on a real device (Samsung galaxy A03)

**Comment by a7med-mahmoud** [comment]
Does it work when you uninstall it?

**Comment by DeepikaSharma5** [comment]
Yes. My app is working fine before install the package and after uninstall it

**Comment by a7med-mahmoud** [comment]
Most likely it's conflicting with `vision-camera-image-labeler` since they both depend on the `com.google.mlkit:image-labeling` Android package. Looking at their GitHub repo. RN ML Kit uses version 17.0.7 while Vision Camera uses version 17.0.5.

**Comment by DeepikaSharma5** [comment]
Oh I'll try removing that package and use `@react-native-ml-kit/image-labeling` directly. But will this package work for iOS also? (Because `vision-camera-image-labeler` is not working well with iOS)

**Comment by a7med-mahmoud** [comment]
Yes, it will. Let me know if you have any issues.

**Comment by DeepikaSharma5** [comment]
Sure. I'll update you soon. Thankyou for your support

**Comment by DeepikaSharma5** [comment]
Hi. I uninstalled `vision-camera-image-labeler` and checked. But still the app is crashing without and error or warning message

**Comment by DeepikaSharma5** [comment]
I think the issue is `vision-camera-face-detector`. That is also using RN ML Kit. That's why it's conflicting

**Comment by a7med-mahmoud** [comment]
Is it working now after removing conflicting packages?

**Comment by a7med-mahmoud** [comment]
What do you mean by shown like this? You mean that `"Object"` thing in the values?
Can you try printing it with this instead?
```js
console.log(JSON.stringify(result, null, 2));
```

**Comment by DeepikaSharma5** [comment]
Oh sorry I mistakenly passed the faces value. I'll remove other conflice packages and try both these packages. I'll check it in android and IOS and let you know. Thankyou for the support 😃
