### ISSUE TITLE
Plugin with id 'maven' not found.

### ISSUE THREAD

**Issue by yamila-fraiman** [a7med-mahmoud/react-native-ml-kit#7]
I'm getting the following error:

`* What went wrong:
A problem occurred evaluating project ':react-native-ml-kit_face-detection'.
> Plugin with id 'maven' not found.
`

**Comment by a7med-mahmoud** [comment]
Can you provide more info? Try running `npx react-native info` in your project directory and comment down the output.

**Comment by yamila-fraiman** [comment]
I found the problem. The maven plugin has been removed since Gradle 7. [DOCS](https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin)

For the moment, I downgrade to 6.9

**Comment by a7med-mahmoud** [comment]
I've removed the dependency on Maven in #8 which solves this issue.
