### ISSUE TITLE
iOS cocoapods versions

### ISSUE THREAD

**Issue by yamila-fraiman** [a7med-mahmoud/react-native-ml-kit#9]
I'm trying to run pod install, and I'm getting the following error. Any help?

```
[!] CocoaPods could not find compatible versions for pod "GoogleMLKit/MLKitCore":
  In Podfile:
    RNMLKitFaceDetection (from `../node_modules/@react-native-ml-kit/face-detection`) was resolved to 1.1.1, which depends on
      GoogleMLKit/FaceDetection (= 2.6.0) was resolved to 2.6.0, which depends on
        GoogleMLKit/MLKitCore (= 2.6.0)

    RNMLKitTextRecognition (from `../node_modules/@react-native-ml-kit/text-recognition`) was resolved to 1.1.1, which depends on
      GoogleMLKit/TextRecognition (= 2.2.0) was resolved to 2.2.0, which depends on
        GoogleMLKit/MLKitCore (= 2.2.0)
```

**Comment by yamila-fraiman** [comment]
I tried that and can't find it. Maybe because your ios version is 9?

**Comment by a7med-mahmoud** [comment]
Make sure you have the latest version of `@react-native-ml-kit/text-recognition` _(currently it's 1.2.0 and the error says you're using 1.1.1)_.

**Comment by yamila-fraiman** [comment]
Thank you again! Sorry for the issue

**Comment by asadMumtaz-YSTL** [comment]
Hey! guys I'm facing this issue when in pod install or pod update

can anyone help me how it resolve.

**using OS: 13.0
react-native: 0.63.4
"react-native-text-recognition": "^1.0.0",**

> [!] CocoaPods could not find compatible versions for pod "react-native-text-recognition":
  In Podfile:
    react-native-text-recognition (from `../node_modules/react-native-text-recognition`)

Specs satisfying the `react-native-text-recognition (from `../node_modules/react-native-text-recognition`)` dependency were found, but they required a higher minimum deployment target.
